[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-client = "2.2.6"
solana-sdk = "2.2.2"
tokio = { version = "1.44.1", features = ["full"] }
bs58 = "0.5.0"
dotenv = "0.15.0"
